// ********RoostGPT********
/*
Test generated by RoostGPT for test test-workflow using AI Type Open AI and AI Model gpt-4o-2024-05-13
ROOST_METHOD_HASH=getRoomBooking_f485001dff
ROOST_METHOD_SIG_HASH=getRoomBooking_2f7d84dab2
```
Scenario 1: Retrieve Room Booking when Room Booking is Set
Details:
  TestName: getRoomBookingWhenRoomBookingIsSet
  Description: This test checks if the `getRoomBooking` method returns the correct room booking value when it has been set prior to the method call.
Execution:
  Arrange: Set the `roomBooking` field to a non-null value (e.g., "RB123456").
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to check if the returned value matches "RB123456".
Validation:
  This assertion verifies that the method correctly returns the value of the `roomBooking` field when it is set. This is significant to ensure that the method works as expected in typical use cases where a room booking has been made.
Scenario 2: Retrieve Room Booking when Room Booking is Null
Details:
  TestName: getRoomBookingWhenRoomBookingIsNull
  Description: This test checks if the `getRoomBooking` method returns null when the `roomBooking` field has not been set.
Execution:
  Arrange: Ensure the `roomBooking` field is null (default value).
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to check if the returned value is null.
Validation:
  This assertion verifies that the method correctly returns null when the `roomBooking` field is not set. This is significant to ensure that the method handles the scenario where no room booking has been made.
Scenario 3: No Side Effects on Logger
Details:
  TestName: getRoomBookingDoesNotAffectLogger
  Description: This test checks if the `getRoomBooking` method does not alter the state of the logger.
Execution:
  Arrange: Retrieve the initial state of the logger.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the logger's state before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the logger, which is crucial for maintaining the integrity of logging functionality.
Scenario 4: No Side Effects on Counter
Details:
  TestName: getRoomBookingDoesNotAffectCounter
  Description: This test checks if the `getRoomBooking` method does not alter the value of the static `counter` field.
Execution:
  Arrange: Retrieve the initial value of the `counter`.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `counter` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `counter`, which is important for maintaining the correct count of operations or instances.
Scenario 5: No Side Effects on ID
Details:
  TestName: getRoomBookingDoesNotAffectID
  Description: This test checks if the `getRoomBooking` method does not alter the value of the final `ID` field.
Execution:
  Arrange: Retrieve the initial value of the `ID` field.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `ID` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `ID`, which is crucial for maintaining the integrity of the identifier.
Scenario 6: No Side Effects on Broker
Details:
  TestName: getRoomBookingDoesNotAffectBroker
  Description: This test checks if the `getRoomBooking` method does not alter the value of the final `broker` field.
Execution:
  Arrange: Retrieve the initial value of the `broker` field.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `broker` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `broker`, which is important for maintaining the correct state of the broker.
Scenario 7: No Side Effects on Begin Date
Details:
  TestName: getRoomBookingDoesNotAffectBeginDate
  Description: This test checks if the `getRoomBooking` method does not alter the value of the final `begin` field.
Execution:
  Arrange: Retrieve the initial value of the `begin` field.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `begin` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `begin` date, which is important for maintaining the correct start date of the booking.
Scenario 8: No Side Effects on End Date
Details:
  TestName: getRoomBookingDoesNotAffectEndDate
  Description: This test checks if the `getRoomBooking` method does not alter the value of the final `end` field.
Execution:
  Arrange: Retrieve the initial value of the `end` field.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `end` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `end` date, which is important for maintaining the correct end date of the booking.
Scenario 9: No Side Effects on Age
Details:
  TestName: getRoomBookingDoesNotAffectAge
  Description: This test checks if the `getRoomBooking` method does not alter the value of the final `age` field.
Execution:
  Arrange: Retrieve the initial value of the `age` field.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `age` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `age`, which is important for maintaining the correct age value.
Scenario 10: No Side Effects on IBAN
Details:
  TestName: getRoomBookingDoesNotAffectIBAN
  Description: This test checks if the `getRoomBooking` method does not alter the value of the final `IBAN` field.
Execution:
  Arrange: Retrieve the initial value of the `IBAN` field.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `IBAN` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `IBAN`, which is important for maintaining the correct IBAN value.
Scenario 11: No Side Effects on Amount
Details:
  TestName: getRoomBookingDoesNotAffectAmount
  Description: This test checks if the `getRoomBooking` method does not alter the value of the final `amount` field.
Execution:
  Arrange: Retrieve the initial value of the `amount` field.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `amount` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `amount`, which is important for maintaining the correct amount value.
Scenario 12: No Side Effects on Bank Payment
Details:
  TestName: getRoomBookingDoesNotAffectBankPayment
  Description: This test checks if the `getRoomBooking` method does not alter the value of the private `bankPayment` field.
Execution:
  Arrange: Retrieve the initial value of the `bankPayment` field.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `bankPayment` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `bankPayment`, which is important for maintaining the correct bank payment value.
Scenario 13: No Side Effects on Activity Booking
Details:
  TestName: getRoomBookingDoesNotAffectActivityBooking
  Description: This test checks if the `getRoomBooking` method does not alter the value of the private `activityBooking` field.
Execution:
  Arrange: Retrieve the initial value of the `activityBooking` field.
  Act: Call the `getRoomBooking` method.
  Assert: Use an assertion to compare the `activityBooking` value before and after the method call.
Validation:
  This assertion ensures that the method does not have any unintended side effects on the `activityBooking`, which is important for maintaining the correct activity booking value.
```
*/
// ********RoostGPT********
package pt.ulisboa.tecnico.softeng.broker.domain;

import org.joda.time.LocalDate;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;
import pt.ulisboa.tecnico.softeng.broker.interfaces.ActivityInterface;
import pt.ulisboa.tecnico.softeng.broker.interfaces.BankInterface;
import pt.ulisboa.tecnico.softeng.broker.interfaces.HotelInterface;
import pt.ulisboa.tecnico.softeng.hotel.domain.Room;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import org.junit.experimental.categories.Category;

@Category({ Categories.getRoomBooking.class, Categories.roostTest1.class, Categories.roostTest2.class })
public class AdventureGetRoomBookingTest {

	private static final Logger logger = LoggerFactory.getLogger(Adventure.class);

	private static final String BROKER_CODE = "BR1234";

	private static final String BROKER_NAME = "BrokerName";

	private static final LocalDate BEGIN_DATE = new LocalDate(2023, 1, 1);

	private static final LocalDate END_DATE = new LocalDate(2023, 1, 10);

	private static final int AGE = 30;

	private static final String IBAN = "PT50000000000000000000000";

	private static final int AMOUNT = 1000;

	private Broker broker;

	private Adventure adventure;

	@Before
	public void setUp() {
		this.broker = new Broker(BROKER_CODE, BROKER_NAME);
		this.adventure = new Adventure(broker, BEGIN_DATE, END_DATE, AGE, IBAN, AMOUNT);
	}

	@Test
	public void testGetRoomBookingWhenRoomBookingIsSet() {
		// Arrange
		String expectedRoomBooking = "RB123456";
		adventure.setRoomBooking(expectedRoomBooking);
		// Act
		String actualRoomBooking = adventure.getRoomBooking();
		// Assert
		assertEquals(expectedRoomBooking, actualRoomBooking);
	}

	@Test
	public void testGetRoomBookingWhenRoomBookingIsNull() {
		// Act
		String actualRoomBooking = adventure.getRoomBooking();
		// Assert
		assertNull(actualRoomBooking);
	}

	@Test
	public void testGetRoomBookingDoesNotAffectLogger() {
		// Arrange
		Logger initialLogger = LoggerFactory.getLogger(Adventure.class);
		// Act
		adventure.getRoomBooking();
		// Assert
		assertSame(initialLogger, LoggerFactory.getLogger(Adventure.class));
	}

	@Test
	public void testGetRoomBookingDoesNotAffectCounter() {
		// Arrange
		int initialCounter = Adventure.getCounter();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertEquals(initialCounter, Adventure.getCounter());
	}

	@Test
	public void testGetRoomBookingDoesNotAffectID() {
		// Arrange
		String initialID = adventure.getID();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertEquals(initialID, adventure.getID());
	}

	@Test
	public void testGetRoomBookingDoesNotAffectBroker() {
		// Arrange
		Broker initialBroker = adventure.getBroker();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertSame(initialBroker, adventure.getBroker());
	}

	@Test
	public void testGetRoomBookingDoesNotAffectBeginDate() {
		// Arrange
		LocalDate initialBeginDate = adventure.getBegin();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertEquals(initialBeginDate, adventure.getBegin());
	}

	@Test
	public void testGetRoomBookingDoesNotAffectEndDate() {
		// Arrange
		LocalDate initialEndDate = adventure.getEnd();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertEquals(initialEndDate, adventure.getEnd());
	}

	@Test
	public void testGetRoomBookingDoesNotAffectAge() {
		// Arrange
		int initialAge = adventure.getAge();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertEquals(initialAge, adventure.getAge());
	}

	@Test
	public void testGetRoomBookingDoesNotAffectIBAN() {
		// Arrange
		String initialIBAN = adventure.getIBAN();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertEquals(initialIBAN, adventure.getIBAN());
	}

	@Test
	public void testGetRoomBookingDoesNotAffectAmount() {
		// Arrange
		int initialAmount = adventure.getAmount();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertEquals(initialAmount, adventure.getAmount());
	}

	@Test
	public void testGetRoomBookingDoesNotAffectBankPayment() {
		// Arrange
		String initialBankPayment = adventure.getBankPayment();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertEquals(initialBankPayment, adventure.getBankPayment());
	}

	@Test
	public void testGetRoomBookingDoesNotAffectActivityBooking() {
		// Arrange
		String initialActivityBooking = adventure.getActivityBooking();
		// Act
		adventure.getRoomBooking();
		// Assert
		assertEquals(initialActivityBooking, adventure.getActivityBooking());
	}

}